apiVersion: v1
kind: namespace
metadata:
  name: flipkart-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app
  namespace: flipkart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipkart-app
  template:
    metadata:
      labels:
        app: flipkart-app
    spec:
      containers:
        - name: flipkart-app
          image: harishnshetty/flipkart-app:1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-app
  namespace: flipkart-app
spec:
  selector:
    app: flipkart-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: HTTPRoute
metadata:
  name: flipkart-app
  namespace: flipkart-app
spec:
  rules:
    - host: flipkart-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flipkart-app
                port:
                  number: 80
